/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");
module.exports = {
  darkMode: ["class"],
  mode: "jit",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      className: {
        "scrollbar-hide": {
          "-ms-overflow-style": "none",
          "scrollbar-width": "none",
        },
        "scrollbar-hide::-webkit-scrollbar": {
          display: "none",
        },
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      keyframes: {
        glitch: {
          "2%, 64%": {
            transform: "translate(2px,0) skew(0deg)",
          },
          "4%, 60%": {
            transform: "translate(-2px,0) skew(0deg)",
          },
          "62%": {
            transform: "translate(0,0) skew(5deg)",
          },
        },
        "glitch-top": {
          "2%, 64%": {
            transform: "translate(2px, -2px)",
          },
          "4%, 60%": {
            transform: "translate(-2px, 2px)",
          },
          "62%": {
            transform: "translate(13px, -1px) skew(-13deg)",
          },
        },
        "glitch-bottom": {
          "2%, 64%": {
            transform: "translate(-2px, 0)",
          },
          "4%, 60%": {
            transform: "translate(-2px, 0)",
          },
          "62%": {
            transform: "translate(-22px, 5px) skew(21deg)",
          },
        },
        "load-bar": {
          "0%": { width: "25%", left: "-25%" },
          "100%": { width: "25%", left: "100%" },
        },
        "accordion-down": {
          from: { height: 0, opacity: 0 },
          to: { height: "var(--radix-accordion-content-height)", opacity: 1 },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: 1 },
          to: { height: 0, opacity: 0 },
        },
        "collapsible-down": {
          from: { height: 0, opacity: 0 },
          to: { height: "var(--radix-collapsible-content-height)", opacity: 1 },
        },
        "collapsible-up": {
          from: {
            height: "var(--radix-collapsible-content-height)",
            opacity: 1,
          },
          to: { height: 0, opacity: 0 },
        },
        "reveal-in": {
          "0%": { width: "0%", color: "hsl(var(--primary-foreground))" },
          "100%": { width: "100%", color: "hsl(var(--primary-foreground))" },
        },
        "reveal-out": {
          "0%": { width: "100%", color: "hsl(var(--primary-foreground))" },
          "100%": { width: "0%", color: "hsl(var(--primary-foreground))" },
        },
        "bg-to-primary": {
          "0%": { backgroundColor: "transparent" },
          "100%": { backgroundColor: "hsl(var(--primary))" },
        },

        "bg-to-transparent": {
          "0%": { backgroundColor: "hsl(var(--primary))" },
          "100%": { backgroundColor: "transparent" },
        },

        "gauge-fill": {
          from: { "stroke-dashoffset": "var(--tw-gauge-fill)", opacity: "1" },
          to: { opacity: "1" },
        },
        jump: {
          "50%": {
            transform: "translateY(-4px)",
            "border-color": "rgb(117, 117, 117)",
          },
          "100%": {
            " ": "translateY(0px)",
            "border-color": "rgb(119, 118, 118)",
          },
        },
        "square-progress": {
          "0%": {
            transform: "translateX(20px) scale(0)",
          },

          "7%": {
            transform: "translateX(0px) scale(1)",
          },
          "57%": {
            transform: "translateX(0px) scale(1)",
          },
          "60%": {
            transform: "translateX(-100px) scale(0)",
          },
          "100%": {
            transform: "translateX(-100px) scale(0)",
          },
        },

        "fade-out-text": {
          "0%": { opacity: 1 },
          "10%": { opacity: 0 },
          "85%": { opacity: 0 },
          "90%": { opacity: 1 },
          "100%": { opacity: 1 },
        },
        "translate-text-1": {
          "0%": {
            transform: "translateX(-30px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "initial",
          },
          "10%": {
            transform: "translateX(12px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "white",
          },
          "25%": {
            transform: "translateX(12px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "white",
          },
          "26%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "white",
          },
          "30%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "0%",
            right: "75%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "45%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "0%",
            right: "75%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "50%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "50%",
            left: "0%",
            right: "50%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "70%": {
            transform: "translateX(0px) rotate(0deg)",
            top: "0%",
            bottom: "50%",
            left: "0%",
            right: "50%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "75%": {
            transform: "translateX(-30px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "initial",
          },
          "100%": {
            transform: "translateX(-30px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "initial",
          },
        },

        "translate-text-2": {
          "0%": {
            transform: "translateX(-16px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "initial",
          },
          "10%": {
            transform: "translateX(26px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "white",
          },
          "25%": {
            transform: "translateX(26px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "white",
          },
          "26%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "white",
          },
          "30%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "25%",
            right: "50%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "45%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "25%",
            right: "50%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "50%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "0%",
            left: "0%",
            right: "50%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "70%": {
            transform: "translateX(0px) rotate(0deg)",
            top: "50%",
            bottom: "0%",
            left: "0%",
            right: "50%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "75%": {
            transform: "translateX(-16px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "initial",
          },
          "100%": {
            transform: "translateX(-16px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "initial",
          },
        },
        "translate-text-3": {
          "0%": {
            transform: "translateX(-8px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "initial",
          },
          "10%": {
            transform: "translateX(34px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "white",
          },
          "25%": {
            transform: "translateX(34px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "white",
          },
          "26%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "white",
          },
          "30%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "50%",
            right: "25%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "45%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "50%",
            right: "25%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "50%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "50%",
            left: "50%",
            right: "0%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "70%": {
            transform: "translateX(0px) rotate(0deg)",
            top: "0%",
            bottom: "50%",
            left: "50%",
            right: "0%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "75%": {
            transform: "translateX(-8px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "initial",
          },
          "100%": {
            transform: "translateX(-8px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "8px",
            height: "34px",
            color: "initial",
          },
        },
        "translate-text-4": {
          "0%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "initial",
          },
          "10%": {
            transform: "translateX(42px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "white",
          },
          "25%": {
            transform: "translateX(42px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "white",
          },
          "26%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "white",
          },
          "30%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "75%",
            right: "0%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "45%": {
            transform: "translateX(0px)",
            top: "0%",
            bottom: "0%",
            left: "75%",
            right: "0%",
            width: "25%",
            height: "100%",
            color: "initial",
          },
          "50%": {
            transform: "translateX(0px)",
            top: "50%",
            bottom: "0%",
            left: "50%",
            right: "0%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "70%": {
            transform: "translateX(0px) rotate(0deg)",
            top: "50%",
            bottom: "0%",
            left: "50%",
            right: "0%",
            width: "50%",
            height: "50%",
            color: "initial",
          },
          "75%": {
            transform: "translateX(0px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "initial",
          },
          "100%": {
            transform: "translateX(0px) rotate(360deg)",
            top: "50%",
            bottom: "50%",
            left: "50%",
            right: "50%",
            width: "14px",
            height: "34px",
            color: "initial",
          },
        },
        "opacity-change-bg": {
          "0%": {
            opacity: "1",
          },
          "20%": {
            opacity: "0",
          },
          "30%": {
            opacity: "1",
          },
          "100%": {
            opacity: "1",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
        "checkbox-in": "reveal-in .2s ease-out .2s forwards",
        "checkbox-out": "reveal-out .2s ease-out forwards",
        "checkbox-bg-in": "bg-to-primary .2s ease-out forwards",
        "checkbox-bg-out": "bg-to-transparent .2s ease-out .2s forwards",

        "gauge-fill": "gauge-fill 1s ease forwards",

        "load-bar": "load-bar 1s linear infinite",
        "square-progress": "square-progress 5s ease-out infinite ",

        "opacity-change-bg": "opacity-change-bg 5s ease-out ",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("tailwindcss-debug-screens"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
    require("tailwind-clip-path"),

    plugin(function ({ matchUtilities }) {
      matchUtilities({
        "gauge-fill": (value) => ({
          "--tw-gauge-fill": value,
        }),
      });
    }),
  ],
};
